parent=base
import=common/keycloak
locales=en,pt-BR

styles=css/bootstrap.min.css css/all.min.css css/stylesheet.css css/projectcore.css
scripts=js/jquery.min.js js/bootstrap.bundle.min.js js/theme.js

meta=viewport==width=device-width,initial-scale=1,shrink-to-fit=no

kcHtmlClass=h-100
kcBodyClass=oxyy-login-register bg-dark

kcLogoIdP-google=fab fa-google
kcLogoIdP-facebook=fab fa-facebook-f
kcLogoIdP-twitter=fab fa-twitter
kcLogoIdP-linkedin=fab fa-linkedin-in
kcLogoIdP-github=fab fa-github
kcLogoIdP-microsoft=fab fa-microsoft
